name: 'WordPress Unit Tests'
description: 'Not necessarily "unit" tests.'
author: 'Kyle B. Johnson'

branding:
  icon: 'list'
  color: 'blue'

inputs:
  php:
    required: true
  wordpress:
    required: true
  
runs:
  using: ubuntu-latest
  steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
        coverage: none
 
    - name: Install dependencies
      run: |
        composer self-update --1
        composer require phpunit/phpunit:5.*
        composer update --prefer-dist --no-interaction --no-suggest

    - name: Execute tests
      run: vendor/bin/phpunit
