name: 'WordPress Unit Tests'
description: 'Not necessarily "unit" tests.'
author: 'Kyle B. Johnson'

branding:
  icon: 'list'
  color: 'blue'

inputs:
  wordpress:
    required: true
  install:
    required: false
    default: 'bin/install-wp-tests.sh'
  
runs:
  using: "composite"
  steps:

    - name: Setup tests
      run: bash ${{ inputs.install }} wordpress_test root root localhost ${{ inputs.wordpress }}
      shell: bash

    - name: Execute tests
      run: vendor/bin/phpunit
      shell: bash
