name: 'WordPress Unit Tests'
description: 'Not necessarily "unit" tests.'
author: 'Kyle B. Johnson'

branding:
  icon: 'list'
  color: 'blue'

inputs:
  wordpress:
    required: true
  
runs:
  using: "composite"
  steps:
 
    - name: Install dependencies
      run: |
        composer self-update --1
        composer require phpunit/phpunit:5.*
        composer update --prefer-dist --no-interaction --no-suggest
      shell: bash

    - name: Execute tests
      run: vendor/bin/phpunit
      shell: bash
