name: CI
 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      php: [ 5.6, 7.2 ]
      wordpress: [ '4.9', '5.0' ]
    steps:
      - uses: kjohnson/wordpress-unit-tests@main
        with:
         php: ${{ matrix.php }}
         wordpress: ${{ matrix.wordpress }}
